--
--    Copyright 2010-2023 the original author or authors.
--
--    Licensed under the Apache License, Version 2.0 (the "License");
--    you may not use this file except in compliance with the License.
--    You may obtain a copy of the License at
--
--       https://www.apache.org/licenses/LICENSE-2.0
--
--    Unless required by applicable law or agreed to in writing, software
--    distributed under the License is distributed on an "AS IS" BASIS,
--    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--    See the License for the specific language governing permissions and
--    limitations under the License.
--
-- // The MyBatis parent POM.
-- Migration SQL that makes the change goes here.
create table "user" (
  id text not null primary key,
  username text not null,
  password text not null,
  email text not null,
  profile text
);

create table post (
  id bigint primary key generated by default as identity,
  user_id text not null,
  foreign key (user_id) references "user" (id),
  content text,
  created_at timestamp not null default current_timestamp
);

-- //@UNDO
-- SQL to undo the change goes here.
drop table "user";

drop table post;
