spring:
  application:
    name: glitter
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mvc:
    problemdetails:
      enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
env:
  api-url: ${API_URL}
  client-url: ${CLIENT_URL}
  storage-url: ${STORAGE_URL}
  storage-bucket-name: ${STORAGE_BUCKET_NAME}
  storage-username: ${STORAGE_USERNAME}
  storage-password: ${STORAGE_PASSWORD}
