spring:
  application:
    name: glitter
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mvc:
    problemdetails:
      enabled: true
  profiles:
    active: ${ENV}
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${COGNITO_CLIENT_ID}
            client-secret: ${COGNITO_CLIENT_SECRET}
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_VoMYsEi7C
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
env:
  api-url: ${API_URL}
  client-url: ${CLIENT_URL}
  storage-url: ${STORAGE_URL}
  storage-bucket-name: ${STORAGE_BUCKET_NAME}
  minio-username: ${MINIO_USERNAME}
  minio-password: ${MINIO_PASSWORD}
  domain: ${DOMAIN}
  cognito-client-id: ${COGNITO_CLIENT_ID}
  cognito-client-secret: ${COGNITO_CLIENT_SECRET}
